### ISSUE TITLE
starting the update tool from options menu throws error

### ISSUE THREAD

**Issue by h3xp** [h3xp/RickDangerousUpdate#22]
starting the update tool from options menu throws this error:
`/dev/fd/63: line 10: update: command not found`
`/dev/fd/63: line 11: update: command not found`
`/dev/fd/63: line 12: update: command not found`
`/dev/fd/63: line 13: update: command not found`
`/dev/fd/63: line 14: update: command not found`
`/dev/fd/63: line 15: update: command not found`
`/dev/fd/63: line 16: update: command not found`
`/dev/fd/63: line 17: update: command not found`
this doesn't seem to affect the process, it just continues to work afterwards, but still something to get rid off

**Comment by LizardWiz** [comment]
Is this via paramiko? Which option (install, update, uninstall)?

**Comment by LizardWiz** [comment]
changed runcmd  from:
    return os.popen(command).read()
to:
    return subprocess.call(["bash","-c",command]).read()

This is because when running from ssh the default shell is not bash so the first "(" after the "bash <" command errors out. subprocess.call can specify which shell to run in and will wait for the process to return. I left the runshell method in there, but I believe it can be taken out.

**Comment by h3xp** [comment]
no this is not via paramiko or ssh at all, this error shows up when you run it from the options menu as I mentioned

**Comment by h3xp** [comment]
This still occurs. After installing improvements it will show up the next times you run the update tool.
